version: 2.1
jobs:
  build:
    docker:
      - image: 'circleci/node:latest'
      - image: 'circleci/mysql:5.7.31'
        environment:
          MYSQL_ROOT_PASSWORD: ''
          MYSQL_DATABASE: 'hostile_world'
          MYSQL_USER: 'traveler'
          MYSQL_PASSWORD: 'travel'
    working_directory: ~/feature
    steps:
      - checkout
      - run: npm install
      - run:
          name: Waiting for MySQL to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z 127.0.0.1 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for MySQL && exit 1
      - run:
          name: Install MySQL CLI; Create schema;
          command: |
            sudo apt-get install default-mysql-client
            mysql -h 127.0.0.1 -u root hostile_world < server/schema.sql
      - run: npm run seed
      - run: sleep 5
      - run: npm start
      - run: sleep 3
      - run: npm test
