version: 2.1
jobs:
  build:
    docker:
      - image: 'circleci/node:latest'
    working_directory: ~/feature
    steps:
      - checkout
      - run: npm install
      - run: npm start
      - run: sleep 3
      - run: npm test